# Generated by Django 4.0.3 on 2022-04-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=20, verbose_name='Тип вопроса')),
            ],
            options={
                'verbose_name': 'Тип вопроса',
                'verbose_name_plural': 'Типы вопросов',
                'ordering': ['type'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting_app.vote', verbose_name='Опрос'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting_app.typequestion', verbose_name='Тип вопроса'),
        ),
    ]
