# Generated by Django 4.0.3 on 2022-04-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_typequestion_alter_question_vote_question_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typequestion',
            options={'ordering': ['name_type'], 'verbose_name': 'Тип вопроса', 'verbose_name_plural': 'Типы вопросов'},
        ),
        migrations.RenameField(
            model_name='typequestion',
            old_name='type',
            new_name='name_type',
        ),
    ]
