# Generated by Django 4.0.3 on 2022-04-20 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_alter_typequestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='type_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting_app.typequestion', verbose_name='Тип вопроса'),
        ),
    ]
