# Generated by Django 4.0.3 on 2022-04-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0006_alter_choice_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_question_audio', models.CharField(max_length=50, verbose_name='Аудио вопрос')),
                ('audio', models.FileField(upload_to='audio/voting_app')),
                ('correct_answer_audio', models.CharField(max_length=50, verbose_name='Правильный ответ на аудио вопрос')),
            ],
            options={
                'verbose_name': 'Аудио вопрос',
                'verbose_name_plural': 'Аудио вопросы',
                'ordering': ['name_question_audio'],
            },
        ),
        migrations.CreateModel(
            name='ImageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_question_image', models.CharField(max_length=50, verbose_name='Графический вопрос')),
                ('image', models.ImageField(upload_to='images/voting_app')),
                ('correct_answer_image', models.CharField(max_length=50, verbose_name='Правильный ответ на графический вопрос')),
            ],
            options={
                'verbose_name': 'Графический вопрос',
                'verbose_name_plural': 'Графические вопросы',
                'ordering': ['name_question_image'],
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_text', models.BooleanField(null=True, verbose_name='Текстовый вопрос')),
                ('type_image', models.BooleanField(null=True, verbose_name='Графический вопрос')),
                ('type_audio', models.BooleanField(null=True, verbose_name='Аудио вопрос')),
                ('type_video', models.BooleanField(null=True, verbose_name='Видео вопрос')),
                ('vote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting_app.vote', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Тип вопроса',
                'verbose_name_plural': 'Типы вопросов',
            },
        ),
        migrations.CreateModel(
            name='VideoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_question_video', models.CharField(max_length=50, verbose_name='Видео вопрос')),
                ('video', models.FileField(upload_to='video/voting_app')),
                ('correct_answer_video', models.CharField(max_length=50, verbose_name='Правильный ответ на видео вопрос')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='voting_app.questiontype', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Видео вопрос',
                'verbose_name_plural': 'Видео вопросы',
                'ordering': ['name_question_video'],
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='type_question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='correct_answer_choice',
            field=models.BooleanField(null=True, verbose_name='Правильный ответ'),
        ),
        migrations.DeleteModel(
            name='TypeQuestion',
        ),
        migrations.AddField(
            model_name='imagequestion',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='voting_app.questiontype', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='audioquestion',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='voting_app.questiontype', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='voting_app.questiontype', verbose_name='Вопрос'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
